spring.application.name=SpringSecurityDemo
server.port=8080

jwt.secret=hf9gEkhblaoPraq2VGUwsKvDl8cQcwUa
jwt.expiration-ms=3600000        # 1 hour

logging.level.org.springframework.security=DEBUG
spring.security.debug=true


